name: PHP Composer

on: [push]

jobs:
  build:

    runs-on: ubuntu-16.04

    steps:
    - uses: actions/checkout@v2
    
    - name: PHP
      run: ls /usr/bin/php* && sudo update-alternatives --set php /usr/bin/php7.0 && php --version

    - name: Composer install
      run: curl -s http://getcomposer.org/installer | php && php composer.phar self-update && php composer.phar install

    - name: Test
      run: php composer.phar check-full
