name: PHP Composer

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Composer install
      run: curl -s http://getcomposer.org/installer | php && php composer.phar self-update && php composer.phar install
    
    - name: XDebug 
      run: pecl install xdebug-2.8.0 && echo "zend_extension=/usr/lib/php/20151012/xdebug.so" >> /etc/php/7.0/cli/php.ini

    - name: Test
      run: php composer.phar check-full
